### ISSUE TITLE
feat(router): Support route groups

### ISSUE THREAD

**Issue by nazo6** [wakujs/waku#560]
I think it would be useful to have route groups like Next.js that can separate layouts without affecting the URL path.

Next.js docs:
https://nextjs.org/docs/app/building-your-application/routing/route-groups

**Comment by dai-shi** [comment]
With `createPages` config router, I think it's possible. Please give it a try.

I'm not sure how we do with fs router, but we probably don't add such complexity. cc: @sandren 
(maybe supporting dynamic layout would be a solution.)
